
import __ASTRO_IMAGE_IMPORT_Z26LMpj from "../../assets/images/partners/quori.png?astroContentImageFlag=&importer=src%2Fcontent%2Feditions%2Ffss2025.md";
import __ASTRO_IMAGE_IMPORT_2gQuyz from "../../assets/images/organizers/andrew-schoen.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fandrew-schoen.md";
import __ASTRO_IMAGE_IMPORT_sP3sz from "../../assets/images/speakers/cindy-bethel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fcindy-bethel.md";
import __ASTRO_IMAGE_IMPORT_Z15ddwd from "../../assets/images/organizers/david-porfirio.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fdavid-porfirio.md";
import __ASTRO_IMAGE_IMPORT_1vN2WC from "../../assets/images/organizers/cynthia-matuszek.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fcynthia-matuszek.md";
import __ASTRO_IMAGE_IMPORT_Z1cfhsm from "../../assets/images/speakers/ken-forbus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fken-forbus.md";
import __ASTRO_IMAGE_IMPORT_24Vb7g from "../../assets/images/organizers/laura-hiatt.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Flaura-hiatt.md";
import __ASTRO_IMAGE_IMPORT_Z1WMOtl from "../../assets/images/speakers/jeremy-marvel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fjeremy-marvel.md";
import __ASTRO_IMAGE_IMPORT_Z1V4TJR from "../../assets/images/organizers/laura-stegner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Flaura-stegner.md";
import __ASTRO_IMAGE_IMPORT_24joJH from "../../assets/images/organizers/ross-mead.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fross-mead.md";
import __ASTRO_IMAGE_IMPORT_DDzAa from "../../assets/images/organizers/saad-elbeleidy.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fsaad-elbeleidy.md";
import __ASTRO_IMAGE_IMPORT_Z4YC50 from "../../assets/images/organizers/ruchen-wen.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fruchen-wen.md";
import __ASTRO_IMAGE_IMPORT_Z1Xuxpb from "../../assets/images/speakers/zhi-tan.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fzhi-tan.md";
import __ASTRO_IMAGE_IMPORT_Z2v84vf from "../../assets/images/organizers/willie-wilson.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fwillie-wilson.md";
export default new Map([["../../assets/images/partners/quori.png?astroContentImageFlag=&importer=src%2Fcontent%2Feditions%2Ffss2025.md", __ASTRO_IMAGE_IMPORT_Z26LMpj], ["../../assets/images/organizers/andrew-schoen.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fandrew-schoen.md", __ASTRO_IMAGE_IMPORT_2gQuyz], ["../../assets/images/speakers/cindy-bethel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fcindy-bethel.md", __ASTRO_IMAGE_IMPORT_sP3sz], ["../../assets/images/organizers/david-porfirio.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fdavid-porfirio.md", __ASTRO_IMAGE_IMPORT_Z15ddwd], ["../../assets/images/organizers/cynthia-matuszek.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fcynthia-matuszek.md", __ASTRO_IMAGE_IMPORT_1vN2WC], ["../../assets/images/speakers/ken-forbus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fken-forbus.md", __ASTRO_IMAGE_IMPORT_Z1cfhsm], ["../../assets/images/organizers/laura-hiatt.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Flaura-hiatt.md", __ASTRO_IMAGE_IMPORT_24Vb7g], ["../../assets/images/speakers/jeremy-marvel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fjeremy-marvel.md", __ASTRO_IMAGE_IMPORT_Z1WMOtl], ["../../assets/images/organizers/laura-stegner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Flaura-stegner.md", __ASTRO_IMAGE_IMPORT_Z1V4TJR], ["../../assets/images/organizers/ross-mead.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fross-mead.md", __ASTRO_IMAGE_IMPORT_24joJH], ["../../assets/images/organizers/saad-elbeleidy.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fsaad-elbeleidy.md", __ASTRO_IMAGE_IMPORT_DDzAa], ["../../assets/images/organizers/ruchen-wen.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fruchen-wen.md", __ASTRO_IMAGE_IMPORT_Z4YC50], ["../../assets/images/speakers/zhi-tan.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fzhi-tan.md", __ASTRO_IMAGE_IMPORT_Z1Xuxpb], ["../../assets/images/organizers/willie-wilson.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fwillie-wilson.md", __ASTRO_IMAGE_IMPORT_Z2v84vf]]);
		